config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :chats do
  post :generate_ad_from_image, on: :member
  resources :messages, only: [:create]
  end

  post "/generate_ad_from_image", to: "jerseys#generate_from_chat", as: :generate_ad_from_image

  get 'teams/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: [:show]
  resources :jerseys, only: [:index, :new, :create, :show]
  resources :chats, only: [:create, :show] do
    resources :messages, only: [:new, :create, :show]
  end
  resources :teams
  resources :jerseys

end

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<div class="banner text-white text-center">
  <div class="container mh-100">
    <h1 class="display-4 mb-4 animate-in">TheSwapClub AI</h1>
    <p class="lead mb-5 animate-in delay-1">
      Pose une question sur un maillot, une année, un joueur…<br />
      Notre intelligence artificielle te répond instantanément.
    </p>
    <%= button_to "Poser une question", chats_path, method: :post, class: "btn btn-dark btn-lg animate-in delay-2" %>
  </div>
</div>